// Code generated from docs/roadmap/spark-rules.json; DO NOT EDIT BY HAND.
// Regenerate with the WP2 generator so the strings stay verbatim.
//
// sparkRules is the in-binary copy of the Spark / unified-memory rule catalog
// (docs/roadmap/spark-support.md section 5). Title, category, severity,
// impact, confidence, why-it-matters and next steps are copied verbatim from
// the knowledge pack; TestSparkRuleTable_MatchesRulesJSON keeps the two in
// lockstep. Analyzer code never types a next step by hand: it calls
// sparkFinding(id, evidence) and, where the catalog documents a variant,
// overrides the severity or confidence afterwards.

package analyzer

import "github.com/thatcooperguy/nvcheckup/pkg/types"

// sparkRule is one catalog row.
type sparkRule struct {
	Title      string
	Category   string
	Severity   types.Severity
	Impact     string
	Confidence int
	Why        string
	Steps      []string
}

var sparkRules = map[string]sparkRule{
	"dgx-spark-detected": {
		Title:      "NVIDIA DGX Spark (GB10) Detected",
		Category:   "gpu",
		Severity:   types.SeverityInfo,
		Impact:     "none",
		Confidence: 95,
		Why:        "Enables unified-memory suppressions and DGX OS pairing rules; OEM units lag NVIDIA OTAs.",
		Steps: []string{
			"No action; memory comes from /proc/meminfo, nvidia-smi memory fields are expected to be [N/A].",
		},
	},
	"rtx-spark-detected": {
		Title:      "NVIDIA RTX Spark (N1X) Detected",
		Category:   "gpu",
		Severity:   types.SeverityInfo,
		Impact:     "none",
		Confidence: 85,
		Why:        "Unified memory and Windows-on-Arm change what nvidia-smi, AdapterRAM (uint32) and CUDA report.",
		Steps: []string{
			"Report total RAM as the GPU pool; record driver version and INF.",
		},
	},
	"grace-hopper-detected": {
		Title:      "NVIDIA Grace Hopper / Grace Blackwell Detected",
		Category:   "gpu",
		Severity:   types.SeverityInfo,
		Impact:     "none",
		Confidence: 85,
		Why:        "Coherent memory but real HBM, ECC, BMC; GB10 suppressions must not apply.",
		Steps: []string{
			"Apply standard datacenter rules.",
		},
	},
	"unified-memory-nvsmi-expected": {
		Title:      "Unified Memory: nvidia-smi Memory Fields Are [N/A] by Design",
		Category:   "hardware",
		Severity:   types.SeverityInfo,
		Impact:     "none",
		Confidence: 95,
		Why:        "Suppresses low-vram, fan, power-limit and PCIe false alarms; cudaMemGetInfo also under-reports.",
		Steps: []string{
			"Use /proc/meminfo MemAvailable (+SwapFree), free -h 'available' or the DGX Dashboard (http://localhost:11000).",
		},
	},
	"unified-memory-pressure": {
		Title:      "Unified Memory Pool Under Pressure",
		Category:   "hardware",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 80,
		Why:        "GPU exhaustion is system RAM exhaustion: OOM killer, frozen SSH or log-less hard reset.",
		Steps: []string{
			"Lower vLLM --gpu-memory-utilization (<= 0.85), --max-model-len and --max-num-seqs, or stop other model servers (ports 8000/30000/11434/8355); re-check MemAvailable after the server has finished loading (no system change).",
			"Optional (root only, transient, momentarily slows I/O while caches refill): sudo sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches'.",
		},
	},
	"unified-memory-swap-in-use": {
		Title:      "Swap in Use on the Unified Memory Pool",
		Category:   "hardware",
		Severity:   types.SeverityInfo,
		Impact:     "persistent",
		Confidence: 80,
		Why:        "Paging the shared pool collapses decode throughput and can hang the box; one community measurement (S36) showed 43-95% token/s loss. Never turn swap off while the workload that filled it is still running.",
		Steps: []string{
			"Reduce the footprint first: lower --gpu-memory-utilization / --max-model-len / concurrency or stop other model servers; re-check once the workload is stopped (no system change).",
			"Do not run swapoff while the workload is loaded: with several GiB swapped it fails (ENOMEM) or forces OOM kills of the running model server.",
			"Advisory: after stopping the workload, and only on dedicated inference hosts: sudo swapoff -a (reversible: sudo swapon -a; not persistent across reboot).",
			"Advisory: (persistent, optional) commenting the swap line out of /etc/fstab or masking the swapfile unit survives reboot; revert by restoring the line and running sudo swapon -a.",
			"Advisory: sudo sysctl vm.swappiness=1 (reversible: sudo sysctl vm.swappiness=60; persistent only if written to /etc/sysctl.d/).",
		},
	},
	"unified-memory-page-cache-hold": {
		Title:      "Page Cache Holding Unified Memory (reclaimable)",
		Category:   "hardware",
		Severity:   types.SeverityInfo,
		Impact:     "reversible",
		Confidence: 60,
		Why:        "Informational: page cache is reclaimable by design and fires on any healthy Spark after an mmap model load. NVIDIA's known-issues page (S3) suggests dropping caches only if cudaMalloc fails while MemAvailable is still large.",
		Steps: []string{
			"No action unless an allocation failed while MemAvailable was large.",
			"Optional (root only, transient, momentarily slows I/O): sudo sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches' then restart the application (S3).",
		},
	},
	"unified-memory-oom-events": {
		Title:      "Out-of-Memory Events on the Unified Memory Pool",
		Category:   "hardware",
		Severity:   types.SeverityWarn,
		Impact:     "irreversible",
		Confidence: 80,
		Why:        "On GB10 these RM failures preceded log-less hard resets with no Xid trail.",
		Steps: []string{
			"Keep >= 8 GiB MemAvailable (the llm-plan floor) and lower --gpu-memory-utilization / context / concurrency (no system change).",
			"Run heavy jobs in a transient scope: systemd-run --scope -p MemoryMax=100G -p MemorySwapMax=0 <cmd> (no persistent change; S33).",
			"Advisory: updating to driver >= 580.159.03 through the DGX Dashboard (July 2026 OTA with improved OOM handling, S4) replaces driver and GSP firmware packages; OTA updates are not designed to be rolled back, so use the Dashboard path and back up first.",
		},
	},
	"dgx-spark-gsp-init-failure": {
		Title:      "GB10 GPU Missing: GSP Firmware Initialization Failed",
		Category:   "driver",
		Severity:   types.SeverityCrit,
		Impact:     "irreversible",
		Confidence: 95,
		Why:        "Driver and GSP firmware are paired per OTA; a plain apt upgrade (580.173.02 on OTA2607 = 580.159.03) leaves the GPU unbootable.",
		Steps: []string{
			"Read-only first: sudo nvidia-spark-ota-check summary shows the torn component; collect sudo nvidia-bug-report.sh before changing anything.",
			"If it persists, open a support case with the bug report (do not reimage as a first step).",
			"Advisory: re-run the DGX Dashboard update (http://localhost:11000), or sudo apt update && sudo apt dist-upgrade && sudo fwupdmgr refresh && sudo fwupdmgr upgrade && sudo reboot (S13). This reinstalls driver packages (revert: apt install the previous versions) and flashes firmware capsules, which cannot be rolled back; unplug AC for 30 s after the firmware step.",
			"Advisory: if the GPU is still missing, downgrade to the OTA-paired driver: sudo apt install nvidia-driver-580-open=<paired> nvidia-firmware-580-<paired> (revert: apt install the newer version again), then sudo apt-mark hold nvidia-driver-580-open (revert: sudo apt-mark unhold nvidia-driver-580-open) and reboot.",
		},
	},
	"dgx-spark-ota-torn": {
		Title:      "DGX OS OTA Is Torn (driver/firmware pairing broken)",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 85,
		Why:        "noble-updates ships newer 580 drivers before the OTA pairs them: GSP failure at next boot or a looping Dashboard update.",
		Steps: []string{
			"Prefer Dashboard updates and let them finish; read-only check: sudo nvidia-spark-ota-check summary.",
			"Advisory: if the same update keeps re-appearing, sudo apt install nvidia-firmware-580-<expected-version> and reboot; this replaces the GSP firmware package to match the OTA-paired driver (revert: apt install the previous nvidia-firmware-580-<version>); back up first (S38).",
		},
	},
	"dgx-spark-driver-too-old": {
		Title:      "Driver Too Old for GB10 (R580 / CUDA 13 required)",
		Category:   "driver",
		Severity:   types.SeverityCrit,
		Impact:     "data-loss",
		Confidence: 90,
		Why:        "sm_121 is unsupported by pre-580 drivers; workloads silently run on CPU.",
		Steps: []string{
			"Advisory: update via the DGX Dashboard (Settings > Updates) or sudo apt update && sudo apt dist-upgrade && sudo fwupdmgr refresh && sudo fwupdmgr upgrade && sudo reboot; this replaces the driver (revert: apt install the previous version) and flashes firmware capsules, which cannot be rolled back.",
			"Last resort, only if a manual driver install left apt unrecoverable: the System Recovery image (docs.nvidia.com/dgx/dgx-spark/system-recovery.html, S121) ERASES ALL DATA on the unit; back up first.",
		},
	},
	"dgx-spark-driver-branch-unsupported": {
		Title:      "Driver Branch Not Supported on DGX Spark",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 75,
		Why:        "Outside NVIDIA validation; breaks OTA pairing.",
		Steps: []string{
			"Advisory: return to the OTA-paired 580.x via the DGX Dashboard (driver downgrade; revert by reinstalling the 590/595 package, which stays unsupported); reboot afterwards.",
		},
	},
	"dgx-spark-foreign-driver-packages": {
		Title:      "Foreign NVIDIA Driver Packages on DGX Spark",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "data-loss",
		Confidence: 80,
		Why:        "Spark has no NVSwitch, so fabricmanager/nvswitch packages are wrong; Secure Boot rejects unsigned DKMS modules; -server branches are not paired with the GSP firmware. The S30 case was closed with a System Recovery image, which erases the unit - that is a last resort, not the first step.",
		Steps: []string{
			"Read-only: dpkg -l | grep -E 'nvidia-driver|nvidia-dkms|nvidia-fabricmanager|nvidia-nvswitch' and sudo nvidia-spark-ota-check summary to list what differs from the image set.",
			"Advisory: remove only the foreign packages (sudo apt purge <pkgs>) and reinstall the image driver set (sudo apt install nvidia-driver-580-open nvidia-firmware-580-<ver> linux-modules-nvidia-580-open-$(uname -r)), then reboot; revert by reinstalling the removed packages.",
			"Last resort, only if the driver set cannot be restored: the System Recovery image (docs.nvidia.com/dgx/dgx-spark/system-recovery.html, S121) ERASES ALL DATA on the unit; back up first.",
		},
	},
	"dgx-spark-cublas-batch-bug": {
		Title:      "cuBLAS/cuDNN Batch Failure on DGX Spark (driver bug)",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "irreversible",
		Confidence: 65,
		Why:        "Batch inference crashes; the fix must arrive via a pairing OTA, not plain apt (see dgx-spark-gsp-init-failure).",
		Steps: []string{
			"Until then reduce batch size or use --enforce-eager where the failing kernel is selected (no system change).",
			"Advisory: update through the DGX Dashboard when it offers >= 580.173.02 (driver + firmware change; OTA updates are not designed to be rolled back); do not pull the driver from apt ahead of the OTA.",
		},
	},
	"dgx-spark-non-nvidia-kernel": {
		Title:      "DGX Spark Not Running the -nvidia Kernel",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 85,
		Why:        "Generic kernels lack r8127, mt7925e, GB10 patches and signed NVIDIA modules.",
		Steps: []string{
			"Boot the installed -nvidia kernel from the GRUB menu (reversible: pick the other entry next boot).",
			"Advisory: sudo apt install linux-nvidia-hwe-24.04 installs a kernel and modules (revert: select the previous kernel in GRUB, then apt remove the added linux-image-*-nvidia / linux-modules-nvidia-580-open-* packages); reboot afterwards.",
		},
	},
	"dgx-spark-ota-outdated": {
		Title:      "DGX OS OTA Outdated",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "irreversible",
		Confidence: 70,
		Why:        "Older OTAs: 6.14 mmap regression, Vulkan broken on 580.95.05, CX-7 power fixes, OOM handling (580.159.03).",
		Steps: []string{
			"Advisory: update via DGX Dashboard (Settings > Updates); OEM units via the OEM channel. An OTA replaces driver, kernel and firmware capsules and is not designed to be rolled back; back up first and keep the unit on AC for the whole update (S13).",
		},
	},
	"dgx-spark-dashboard-unhealthy": {
		Title:      "DGX Dashboard / fwupd Unhealthy",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 75,
		Why:        "The Dashboard is the primary update path; a hung fwupd makes Updates spin forever.",
		Steps: []string{
			"Read-only: systemctl status dgx-dashboard dgx-dashboard-admin fwupd; fwupdmgr --version.",
			"Advisory: sudo apt install --only-upgrade fwupd && sudo systemctl restart fwupd dgx-dashboard dgx-dashboard-admin (package upgrade plus service restarts; a restart interrupts an in-progress Dashboard update, so wait for one to finish; the services come back at boot, no revert needed).",
		},
	},
	"dgx-spark-firmware-behind": {
		Title:      "DGX Spark Firmware Behind the Current Release",
		Category:   "hardware",
		Severity:   types.SeverityWarn,
		Impact:     "irreversible",
		Confidence: 60,
		Why:        "2026 firmware waves target USB-PD and EC stability; NVIDIA staff in S46 recommend current firmware plus a cold power cycle for the power-limited state (some users report it fixed; one user in S110 reports EC 3.5.8 worsened fan ramping).",
		Steps: []string{
			"sudo fwupdmgr refresh && sudo fwupdmgr get-upgrades (read-only).",
			"Advisory: apply firmware via the DGX Dashboard or your vendor channel, then cold power-cycle with the PSU unplugged; a firmware flash cannot be undone by NVCheckup and a downgrade is only sometimes offered (fwupdmgr downgrade, S110); check fwupdmgr get-history for 'Update State: Success'.",
		},
	},
	"gb10-pd-power-wedge": {
		Title:      "GB10 Power-Limited (USB-C PD wedge signature)",
		Category:   "performance",
		Severity:   types.SeverityCrit,
		Impact:     "irreversible",
		Confidence: 85,
		Why:        "Community-observed signature (S46 forum thread; S47/S120 community repos; S6/S108/S123 threads) of a wedged USB-C PD contract: the SoC sits in a ~13-30 W fallback, 3-5x slower, -lgc has no effect and a warm reboot does not clear it. NVIDIA support in S46 confirmed the cold power cycle as the recovery and pointed a persistent OEM case to RMA (S107).",
		Steps: []string{
			"Cold drain (no software change): shut down, unplug the PSU from wall AND unit, unplug all USB-C, hold power 30 s, wait 60 s, reconnect only the supplied adapter, re-test under load.",
			"If it recurs: sudo nvidia-bug-report.sh and open a support/RMA case (NVIDIA for FE, the OEM for OEM units).",
			"Advisory: update firmware via the DGX Dashboard or your vendor channel (firmware flashes cannot be rolled back), cold-drain again, and avoid suspend/resume (S51).",
		},
	},
	"gb10-logless-hard-poweroff": {
		Title:      "Log-less Hard Power-Off on GB10",
		Category:   "hardware",
		Severity:   types.SeverityWarn,
		Impact:     "irreversible",
		Confidence: 70,
		Why:        "Community reports (S48 repo, S105 thread) describe the EC cutting power under ~90 W sustained GPU load before the kernel can log; S48 quotes NVIDIA staff calling it 'a known issue' with a clock cap as the workaround, and RMAs were granted for fieldiag PowerStress failures (MODS-020000610139, S106). These are community reports, not an NVIDIA statement.",
		Steps: []string{
			"Use the supplied 240 W adapter directly in the wall, unstack, keep ambient 5-30 C (S20); reduce memory over-commit (same signature).",
			"Advisory: update firmware via the DGX Dashboard, then cold power-cycle (firmware flashes cannot be rolled back).",
			"Advisory: (community mitigation from S48, never applied by NVCheckup) sudo nvidia-smi -lgc 300,2200 caps clocks at a ~1-10% throughput cost (S48 estimates 1-5%) and does not persist across reboot unless you add a systemd unit; revert with sudo nvidia-smi -rgc.",
			"Advisory: (fieldiag, S16) sudo apt install dgx-spark-fieldiag; partnerdiag requires Secure Boot disabled in UEFI setup (Security > Secure Boot) - re-enable it afterwards; sudo init 3 ends the graphical session (save work first; a reboot restores it); then sudo /opt/nvidia/dgx-spark-fieldiag/partnerdiag --field.",
		},
	},
	"gb10-acpi-thermal-zone-hot": {
		Title:      "GB10 ACPI Thermal Zone Hot",
		Category:   "performance",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 65,
		Why:        "A single thread (S49) reports a package sensor up to ~20 C above the GPU reading; 96-97 C zones with quiet fans preceded hard power-offs in S49/S109/S110 (community reports).",
		Steps: []string{
			"Improve airflow: unstack, unblock vents, ambient 5-30 C (S20); read-only: fwupdmgr get-devices for the EC level.",
			"OEM units: contact the OEM (own firmware track).",
			"Advisory: (fieldiag, S16) partnerdiag requires Secure Boot disabled in UEFI setup - re-enable it afterwards; sudo init 3 ends the graphical session; then sudo /opt/nvidia/dgx-spark-fieldiag/partnerdiag --field.",
		},
	},
	"gb10-clock-cap-active": {
		Title:      "GB10 Clock Cap Active",
		Category:   "performance",
		Severity:   types.SeverityInfo,
		Impact:     "reversible",
		Confidence: 85,
		Why:        "Explains lower clocks so they are not mistaken for throttling; does not fix the PD wedge.",
		Steps: []string{
			"No action if you set the cap deliberately (S48 community mitigation).",
			"Advisory: sudo nvidia-smi -rgc removes the cap only if you set it and no longer want it (revert: re-run your -lgc command). A gb10-clock-cap.service unit re-applies it at boot: sudo systemctl disable --now gb10-clock-cap.service (revert: sudo systemctl enable --now gb10-clock-cap.service).",
		},
	},
	"dgx-spark-suspend-failure": {
		Title:      "Suspend/Resume Failure on DGX Spark",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 75,
		Why:        "Suspend is disabled by default on Spark and s2idle does not complete; resume triggers the PD wedge; headless boxes suspend from the login screen and drop Wi-Fi.",
		Steps: []string{
			"Keep suspend off: GNOME Settings > Power > Automatic Suspend = Off (reversible in the same dialog).",
			"Re-test clocks after any suspend (gb10-pd-power-wedge).",
			"Advisory: sudo systemctl mask sleep.target suspend.target (persistent; revert: sudo systemctl unmask sleep.target suspend.target).",
			"Advisory: (headless, S52) sudo -u gdm dbus-run-session gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing' (persistent; revert: sudo -u gdm dbus-run-session gsettings reset org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type).",
		},
	},
	"dgx-spark-cx7-slot-power-benign": {
		Title:      "ConnectX-7 Slot Power Message Is Benign",
		Category:   "hardware",
		Severity:   types.SeverityInfo,
		Impact:     "none",
		Confidence: 90,
		Why:        "Prevents a false power fault; only fatal AER or a ~13 Gb/s link matters.",
		Steps: []string{
			"Ignore unless gb10-pd-power-wedge or cx7-link-speed-degraded also fires.",
		},
	},
	"arm64-cuda12-wheel-on-cuda13": {
		Title:      "CUDA 12 Wheel on a CUDA 13 Host",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 80,
		Why:        "A cu12 wheel may import yet miss sm_121 kernels (sm121-kernel-missing) or fail to import when it expects a system libcudart.so.12; a frequent GB10 setup failure (S33 and S118 community setup guides).",
		Steps: []string{
			"pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu130 (reversible: reinstall the previous wheel); vLLM +cu130 aarch64 wheel or https://wheels.vllm.ai/nightly/cu130; SGLang lmsysorg/sglang:latest-cu130.",
			"Remove stray nvidia-*-cu12 pip packages from the venv (reversible: pip install them again).",
		},
	},
	"sm121-torch-capability-warning-benign": {
		Title:      "PyTorch Capability 12.1 Warning Is Benign",
		Category:   "cuda",
		Severity:   types.SeverityInfo,
		Impact:     "none",
		Confidence: 90,
		Why:        "Stops users rebuilding PyTorch for sm_121 or blaming the warning for unrelated failures.",
		Steps: []string{
			"No action; confirm torch.version.cuda starts with 13 and a matmul runs on cuda.",
		},
	},
	"sm121-kernel-missing": {
		Title:      "No sm_121 Kernels for GB10/N1X",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 80,
		Why:        "Kernel launches fail or fall back to slow generic paths: a vLLM build without native sm_121 cubins gave 13 tok/s vs 48.6 tok/s after rebuild (~4x, single measurement, S54).",
		Steps: []string{
			"Use cu130 aarch64 wheels or NGC images with sm_121 (pytorch >= 25.10, vllm 26.xx, tensorrt-llm >= 1.2); rebuild with TORCH_CUDA_ARCH_LIST=\"12.1+PTX\" (sm_120 SASS also runs on 12.1, S53/S119) or CMAKE_CUDA_ARCHITECTURES=121a-real for llama.cpp; verify cuobjdump --list-elf <lib.so> | grep -c sm_12 (all reversible: reinstall the previous wheel).",
		},
	},
	"sm121-triton-ptxas-stale": {
		Title:      "Triton Bundles a Stale ptxas (no sm_121a)",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 75,
		Why:        "torch.compile, FlashInfer/Triton attention and TRT-LLM NVFP4 kernels JIT at runtime and abort.",
		Steps: []string{
			"export TRITON_PTXAS_PATH=/usr/local/cuda/bin/ptxas (mpirun -x TRITON_PTXAS_PATH for TRT-LLM); TORCH_CUDA_ARCH_LIST=\"12.1+PTX\" (environment only, reversible).",
		},
	},
	"arm64-flash-attn-no-wheel": {
		Title:      "flash_attn Has No aarch64 Wheel",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 70,
		Why:        "Import errors break attn_implementation='flash_attention_2'; community guidance for Blackwell consumer parts (S33, S55) is SDPA.",
		Steps: []string{
			"pip uninstall flash-attn; use attn_implementation=\"sdpa\" or the NGC container's bundled kernels (reversible).",
			"If FA2 is required, build from source targeting 12.1: TORCH_CUDA_ARCH_LIST=\"12.1+PTX\" FLASH_ATTENTION_FORCE_BUILD=TRUE (the one arch recommendation, shared with sm121-kernel-missing; if the build script rejects 12.1, the sm_120 build FLASH_ATTN_CUDA_ARCHS=\"120\" also runs on 12.1, S119).",
		},
	},
	"arm64-container-amd64-image": {
		Title:      "amd64 Container Image on an arm64 Host",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "none",
		Confidence: 85,
		Why:        "The container cannot start and users blame the GPU/driver.",
		Steps: []string{
			"Pull an arm64 tag (docker manifest inspect must list linux/arm64); check the DGX Spark Collection on NGC before pulling NIMs.",
		},
	},
	"sm121-ngc-image-too-old": {
		Title:      "NGC Image Predates CUDA 13 / sm_121",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 75,
		Why:        "nvidia-smi works inside but torch.cuda.is_available() is False or kernels fail.",
		Steps: []string{
			"Use nvcr.io/nvidia/pytorch:25.11-py3+, nvcr.io/nvidia/vllm:26.05-py3, tensorrt-llm/release:1.3.0rc13, lmsysorg/sglang:latest-cu130; pin tags (pulling a newer image is reversible).",
		},
	},
	"docker-snap-gpu-blocked": {
		Title:      "Snap Docker Cannot Use the GPU",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "data-loss",
		Confidence: 85,
		Why:        "Snap-confined Docker cannot load host NVML; the DGX OS recipe (NVIDIA moderator in S58) is docker-ce plus nv-docker-gpus / nv-docker-options.",
		Steps: []string{
			"Advisory: (data loss) sudo snap remove docker deletes the snap's containers, images and volumes; first export what you need (docker save / docker export) or sudo snap save docker to keep a snapshot restorable with snap restore.",
			"Advisory: sudo apt install docker-ce docker-ce-cli docker-compose-plugin nv-docker-gpus nv-docker-options (S58; package install, revert: apt remove them).",
		},
	},
	"docker-cdi-spec-missing": {
		Title:      "Docker CDI Spec / nvidia Runtime Missing",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 70,
		Why:        "Factory images (toolkit 1.19.0) shipped without the CDI spec unit; --gpus all works without the named runtime, compose files using runtime: nvidia do not.",
		Steps: []string{
			"Advisory: sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml writes a new file (revert: sudo rm /etc/cdi/nvidia.yaml).",
			"Advisory: sudo nvidia-ctk runtime configure --runtime=docker edits /etc/docker/daemon.json (back it up first; revert by restoring the copy), and sudo systemctl restart docker stops every running container unless live-restore is enabled - do it between jobs.",
		},
	},
	"onnxruntime-cuda-provider-missing": {
		Title:      "onnxruntime Has No CUDAExecutionProvider",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 70,
		Why:        "ONNX-backed pipelines run on CPU with no error.",
		Steps: []string{
			"Advisory: pip uninstall onnxruntime (reversible); install a community sm_121 onnxruntime-gpu build or build ORT 1.27+ (CUDA 13.0 + cuDNN 9) with --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=121 after sudo apt install libcudnn9-cuda-13 libcudnn9-dev-cuda-13 (package install; S61) (revert: sudo apt remove libcudnn9-cuda-13 libcudnn9-dev-cuda-13).",
		},
	},
	"gb10-k8s-device-plugin-old": {
		Title:      "Kubernetes Device Plugin Too Old for GB10",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 60,
		Why:        "Node advertises zero nvidia.com/gpu (CrashLoopBackOff); one S8 comment (2026-03-31) reports MPS also failing ('getpwuid() failed for 0') so only time-slicing worked (single report).",
		Steps: []string{
			"Advisory: (cluster-wide change) upgrade k8s-device-plugin >= v0.17.4 / dra-driver >= v0.4.0 / HAMi with preConfiguredDeviceMemory (revert: helm rollback <release>); do not rely on the gpu.memory label.",
		},
	},
	"cx7-not-enumerated": {
		Title:      "ConnectX-7 Not Enumerated",
		Category:   "network",
		Severity:   types.SeverityCrit,
		Impact:     "persistent",
		Confidence: 85,
		Why:        "No 200 Gb/s link, RoCE or multi-node NCCL; 6.17.0-1021/1029-nvidia have a hotplug regression that drops the NIC 5-22 s after boot, retraining failures needed RMA.",
		Steps: []string{
			"Cold power cycle with power and QSFP unplugged (no software change).",
			"Persistent 'retraining failed' -> fieldiag (Advisory: partnerdiag needs Secure Boot disabled in UEFI setup, re-enable it afterwards) and RMA.",
			"Advisory: on 6.17.0-1021/1029-nvidia move to the fixed 6.17 kernel (>= 6.17.0-1031-nvidia, spec 2.1) via the DGX Dashboard or apt (kernel change; revert by selecting the previous entry in GRUB). Pinning linux-image-6.14.0-1015-nvidia plus matching nvidia-580-open modules is a stop-gap kernel downgrade only: it makes dgx-spark-ota-outdated fire (revert: apt-mark unhold and reinstall the current kernel).",
		},
	},
	"cx7-twin-link-mismatch": {
		Title:      "ConnectX-7 Twin Link State Mismatch",
		Category:   "network",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 75,
		Why:        "Each cage is two 100 Gb/s PCIe x4 twins; one twin down caps the link at ~100 Gb/s; the Jan-2026 hot-plug power file can keep lanes from training.",
		Steps: []string{
			"Reseat an approved DAC (Amphenol NJAAKK-N911/NJAAKK0006, Luxshare LMTQF022-SD-R, S17); reboot both nodes with the cable attached (no configuration change).",
			"Advisory: (community workaround from S63, not NVIDIA guidance) if lanes never train, sudo rm -f /etc/nvidia/cx7-hotplug-enabled on both nodes and reboot; restore the NVIDIA-managed file with sudo touch /etc/nvidia/cx7-hotplug-enabled and reboot.",
		},
	},
	"cx7-link-speed-degraded": {
		Title:      "ConnectX-7 Link Speed Degraded",
		Category:   "network",
		Severity:   types.SeverityWarn,
		Impact:     "none",
		Confidence: 80,
		Why:        "A 100G cable/switch port or firmware regression halves NCCL bandwidth; the ~13 Gb/s state needs a reboot with the cable attached or firmware + cold drain.",
		Steps: []string{
			"Use a >= 200 Gb/s cable; switch ports at 200G, autoneg off, one L2 bridge, MTU 9000 (switch-side settings, outside this host); sudo fwupdmgr get-upgrades (read-only).",
		},
	},
	"cx7-up-no-ip": {
		Title:      "ConnectX-7 Port Up Without an IPv4 Address",
		Category:   "network",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 75,
		Why:        "NCCL and discover-sparks cannot use an unaddressed link; ip addr add is lost at reboot; with two cables all four twins need addresses.",
		Steps: []string{
			"Advisory: write /etc/netplan/40-cx7.yaml (chmod 600) with dhcp4: no and a static address per twin, then sudo netplan apply (persistent network change; revert: sudo rm /etc/netplan/40-cx7.yaml && sudo netplan apply) (S18).",
		},
	},
	"cx7-twins-same-subnet": {
		Title:      "ConnectX-7 Twins Share a Subnet or Bond",
		Category:   "network",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 85,
		Why:        "Same-subnet or bonded twins break routing/ARP, RoCE reachability and NCCL autodiscovery ('Interfaces X and Y share the same subnet').",
		Steps: []string{
			"Advisory: one /24 per twin on both nodes (192.168.100.x / 192.168.101.x) in netplan and remove bonds (persistent network change; revert by restoring the previous netplan file and sudo netplan apply) (S65); list both twins in NCCL_IB_HCA.",
		},
	},
	"cx7-mtu-mismatch": {
		Title:      "ConnectX-7 MTU Mismatch",
		Category:   "network",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 70,
		Why:        "Silent jumbo-frame drops; a 3-node NCCL failure and the 3 GB/s plateau were traced to 1500 vs 9000.",
		Steps: []string{
			"Advisory: mtu: 9000 on all twins on every node in netplan (persistent; revert: remove the mtu key and sudo netplan apply); switch l2mtu 9216; verify with ping -M do -s 8972 <peer> (read-only).",
		},
	},
	"nccl-env-misconfigured": {
		Title:      "NCCL Environment Misconfigured for DGX Spark",
		Category:   "network",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 75,
		Why:        "Each misstep drops the pair from ~22-24 GB/s busbw to ~12 GB/s (one twin) or 1-3 GB/s (sockets); NCCL < 2.28 lacks sm_121 and hangs.",
		Steps: []string{
			"export NCCL_IB_HCA={active_twins} - both twins of the cabled cage as the collector saw them ACTIVE (port 0: rocep1s0f0,roceP2p1s0f0; port 1: rocep1s0f1,roceP2p1s0f1) - NCCL_SOCKET_IFNAME={cabled_netdev} NCCL_IB_GID_INDEX=3 NCCL_NET_PLUGIN=none; rings: NCCL_IB_SUBNET_AWARE_ROUTING=1 NCCL_IB_MERGE_NICS=0 (environment only, reversible).",
			"NCCL < 2.28 lacks sm_121 support and collectives hang (community benchmark S102; stock NGC 2.27.7): build NCCL v2.30.7-1 with -gencode=arch=compute_121,code=sm_121 per the NVIDIA playbook (S67); confirm 'NET/IB' in NCCL_DEBUG=INFO.",
		},
	},
	"nccl-gdr-assumed": {
		Title:      "GPUDirect RDMA Assumed (unsupported on Spark)",
		Category:   "network",
		Severity:   types.SeverityInfo,
		Impact:     "reversible",
		Confidence: 80,
		Why:        "GPUDirect RDMA, nvidia-peermem, dma-buf and GDRCopy are unsupported (cudaMalloc memory is not CPU/PCIe coherent); assuming GDR causes init hangs.",
		Steps: []string{
			"NCCL_NET_GDR_LEVEL=0, NCCL_DMABUF_ENABLE=0 (environment only, reversible); do not install nvidia-peermem/GDRCopy; RDMA buffers via cudaHostAlloc + ib_reg_mr (S69).",
		},
	},
	"cx7-mdns-hostname-conflict": {
		Title:      "mDNS Hostname Conflict on the Cluster Fabric",
		Category:   "network",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 80,
		Why:        "Cabled twins without DHCP flap and avahi sees its own announcements as conflicts; spark-xxxx.local becomes unreachable for NVIDIA Sync and discover-sparks needs avahi-browse.",
		Steps: []string{
			"Advisory: static addresses on the twins (netplan dhcp4: no; persistent, revert by restoring the previous netplan and sudo netplan apply).",
			"Advisory: sudo apt-get install -y avahi-utils (package install; revert: apt remove avahi-utils).",
			"Advisory: sudo systemctl restart avahi-daemon (brief mDNS outage; no revert needed).",
		},
	},
	"cx7-firewall-blocks-cluster": {
		Title:      "Firewall Blocks Cluster Traffic",
		Category:   "network",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 60,
		Why:        "Blocks mDNS discovery, mpirun SSH launch and torch.distributed rendezvous ('Watchdog caught collective operation timeout').",
		Steps: []string{
			"Advisory: sudo ufw allow from <fabric-subnet>/24 (both twins) or at least sudo ufw allow 29500/tcp, 5353/udp, 22/tcp (persistent firewall change; revert: sudo ufw status numbered then sudo ufw delete <n>, or sudo ufw delete allow from <fabric-subnet>/24).",
		},
	},
	"rtx-spark-driver-developer-preview": {
		Title:      "RTX Spark Developer Preview Driver",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 80,
		Why:        "NVIDIA lists the preview stack as pre-release, not for production or benchmarking (S26 release notes), with the known issue 'Possible system instability during PyTorch build workflows' (S24 landing page). (The v1 '~2 min blank display during install' claim had no source and was dropped.)",
		Steps: []string{
			"Check the RTX Spark Developer Preview thread (S24) and OEM/Windows Update for a production Arm64 driver (read-only).",
			"Advisory: installing a different driver replaces the Developer Preview package (revert: reinstall the 616.00 DP package from the S24 thread).",
		},
	},
	"woa-cuda-toolkit-not-native": {
		Title:      "CUDA Toolkit Is Not Native Windows Arm64",
		Category:   "cuda",
		Severity:   types.SeverityWarn,
		Impact:     "reversible",
		Confidence: 80,
		Why:        "An emulated toolkit targets x64 and cannot exercise the native Arm64 CUDA runtime.",
		Steps: []string{
			"Install CUDA 13.4 DP (Windows ARM64) or cross-compile from x86_64 (toolkit install, reversible via Settings > Apps); use pinned host memory (S26 documents a pageable-memory slowdown).",
		},
	},
	"woa-nvcheckup-emulated": {
		Title:      "NVCheckup Running Under x64 Emulation (Prism)",
		Category:   "gpu",
		Severity:   types.SeverityWarn,
		Impact:     "none",
		Confidence: 95,
		Why:        "Emulated processes get emulated CPU details and registry/filesystem redirection.",
		Steps: []string{
			"Run nvcheckup-windows-arm64.exe.",
		},
	},
	"woa-windows-build-too-old": {
		Title:      "Windows Build Too Old for RTX Spark",
		Category:   "driver",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 80,
		Why:        "Prism AVX/AVX2 emulation (S73) and downloadable Windows ML execution providers incl. NvTensorRtRtx (S115) require 24H2 (26100) or later.",
		Steps: []string{
			"Advisory: update Windows to 24H2 or later via Settings > Windows Update (feature update; Windows keeps a 10-day rollback under Settings > System > Recovery); 26H1 is device-scoped, not an in-place update (S74).",
		},
	},
	"wsl-linux-driver-installed": {
		Title:      "Linux NVIDIA Driver Installed Inside WSL",
		Category:   "wsl",
		Severity:   types.SeverityWarn,
		Impact:     "persistent",
		Confidence: 85,
		Why:        "CUDA in WSL comes from the Windows driver; NVIDIA: 'users must not install any NVIDIA GPU Linux driver within WSL 2'.",
		Steps: []string{
			"Advisory: remove the in-distro driver packages (sudo apt purge 'nvidia-driver-*' 'nvidia-dkms-*'; revert: reinstall them, although NVIDIA says they must not be installed inside WSL, S75).",
			"Advisory: update the Windows driver (>= 616.00 on RTX Spark; host driver change, revert: reinstall the previous package); use aarch64 cu130 wheels in an aarch64 distro.",
		},
	},
	"rtx-spark-linux-unsupported": {
		Title:      "RTX Spark (N1X) on Linux Is Unsupported",
		Category:   "gpu",
		Severity:   types.SeverityWarn,
		Impact:     "none",
		Confidence: 75,
		Why:        "Closest reference is DGX Spark (Ubuntu 24.04, R580 open, CUDA 13.0, sm_121); laptop drivers unverified.",
		Steps: []string{
			"Treat results as best-effort; expect nvidia-smi memory fields [N/A] as on GB10.",
		},
	},
}

// legacyImpact is the impact value of every pre-Spark rule, judged from the
// most invasive step each rule prints (firmware/BIOS flashes are
// irreversible, package and driver installs persistent, settings toggles
// reversible, pure checks none). It mirrors knowledge/rules.json and is
// applied by Analyze so every emitted finding carries a non-empty Impact.
var legacyImpact = map[string]string{
	"no-nvidia-gpu":                  "persistent",
	"hybrid-gpu":                     "reversible",
	"driver-not-detected":            "persistent",
	"nvidia-smi-missing":             "persistent",
	"jetson-detected":                "none",
	"driver-resets-4101":             "persistent",
	"nvlddmkm-errors":                "irreversible",
	"whea-corrected":                 "irreversible",
	"whea-errors":                    "irreversible",
	"power-plan-suboptimal":          "reversible",
	"hags-enabled":                   "reversible",
	"recent-windows-updates":         "persistent",
	"nvidia-app-detected":            "reversible",
	"overlay-software":               "reversible",
	"no-nvidia-gpu-encoding":         "persistent",
	"nouveau-active":                 "persistent",
	"nvidia-module-not-loaded":       "reversible",
	"no-dev-nvidia":                  "reversible",
	"libcuda-not-found":              "persistent",
	"dkms-failure":                   "persistent",
	"secureboot-blocking":            "persistent",
	"secureboot-ok":                  "none",
	"cuda-mismatch":                  "persistent",
	"cuda-toolkit-minor-newer":       "persistent",
	"pytorch-cuda-newer-than-driver": "reversible",
	"pytorch-cuda-newer-but-working": "persistent",
	"pytorch-import-error":           "reversible",
	"pytorch-cpu-only":               "reversible",
	"pytorch-cuda-no-gpu":            "none",
	"pytorch-cuda-ok":                "none",
	"tensorflow-import-error":        "reversible",
	"tensorflow-no-gpu":              "reversible",
	"tensorflow-gpu-ok":              "none",
	"wsl-no-dxg":                     "persistent",
	"wsl-dxg-smi-fail":               "reversible",
	"low-vram":                       "none",
	"thermal-throttling":             "reversible",
	"gpu-power-cap":                  "reversible",
	"gpu-clock-slowdown":             "reversible",
	"gpu-running-hot":                "reversible",
	"fan-not-spinning":               "reversible",
	"pcie-downshift":                 "irreversible",
	"pcie-width-reduced":             "none",
	"pcie-idle-power-saving":         "none",
	"mixed-refresh-rate":             "reversible",
	"display-chain-complex":          "none",
	"high-jitter":                    "none",
	"icmp-filtered":                  "none",
	"packet-loss":                    "none",
	"wifi-congestion":                "reversible",
	"dns-slow":                       "reversible",
	"xid-errors":                     "persistent",
	"llvmpipe-fallback":              "persistent",
	"wayland-nvidia-issue":           "reversible",
	"gpu-power-state-stuck":          "reversible",
	"network-ping-unavailable":       "persistent",
	"network-healthy":                "none",
}
