package remediate

import (
	"os/exec"
	"strings"
)

// This file holds the OS-independent parts of the blacklist-nouveau action so
// they can be unit-tested on any platform. The privileged file and command
// operations live in actions_linux.go.

// nouveauBlacklistPath is the modprobe drop-in nvcheckup manages.
const nouveauBlacklistPath = "/etc/modprobe.d/blacklist-nouveau.conf"

// nouveauBlacklistContent is the exact file content written by the action.
// Every line must satisfy validateNouveauContent so the same content can be
// round-tripped through the journal and restored by undo.
const nouveauBlacklistContent = "# Generated by NVCheckup - blacklist nouveau so the NVIDIA proprietary driver can load\n" +
	"blacklist nouveau\n" +
	"options nouveau modeset=0\n"

// initramfsTool describes how to rebuild the initramfs on a distro family.
// Blacklisting nouveau only in /etc/modprobe.d is not enough on Ubuntu or
// Fedora because the early-boot image carries its own copy of the modprobe
// configuration; without a rebuild nouveau still loads from the initramfs.
type initramfsTool struct {
	Name string
	Args []string
}

// initramfsTools lists the known rebuild tools in preference order:
// Debian/Ubuntu, Fedora/RHEL/openSUSE, Arch.
var initramfsTools = []initramfsTool{
	{Name: "update-initramfs", Args: []string{"-u"}},
	{Name: "dracut", Args: []string{"-f"}},
	{Name: "mkinitcpio", Args: []string{"-P"}},
}

// lookPath resolves a binary on PATH. It is a variable so tests can control
// which initramfs tool appears to be installed.
var lookPath = exec.LookPath

// detectInitramfsTool returns the first known initramfs rebuild tool found on
// PATH, or ok=false when none is installed.
func detectInitramfsTool(look func(string) (string, error)) (initramfsTool, bool) {
	for _, t := range initramfsTools {
		if _, err := look(t.Name); err == nil {
			return t, true
		}
	}
	return initramfsTool{}, false
}

// packageListHasNvidiaDriver scans package-manager output for an installed
// NVIDIA kernel driver package. It understands:
//   - dpkg -l: lines beginning with "ii" followed by the package name
//   - rpm -qa / pacman -Q: one package per line
//
// It deliberately looks for driver packages (nvidia-driver-*, nvidia-dkms,
// akmod-nvidia, kmod-nvidia, xorg-x11-drv-nvidia, nvidia, nvidia-open,
// nvidia-lts) rather than any package containing "nvidia", because utilities
// such as nvidia-settings or libnvidia-* can be present without a driver.
func packageListHasNvidiaDriver(output string) bool {
	for _, line := range strings.Split(output, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		name := fields[0]
		// dpkg -l format: "ii  nvidia-driver-550  550.54.14-0ubuntu0  amd64  ..."
		// A two-letter first column is a dpkg status code; only "ii" (installed)
		// and "hi" (installed, on hold) count. "rc", "un", etc. mean removed or
		// never installed. No NVIDIA driver package has a two-letter name, so
		// this cannot mis-skip an rpm or pacman line.
		if len(fields) >= 2 && len(name) == 2 {
			if name != "ii" && name != "hi" {
				continue
			}
			name = fields[1]
		}
		// Strip any dpkg architecture qualifier ("nvidia-dkms-550:amd64").
		if i := strings.IndexByte(name, ':'); i > 0 {
			name = name[:i]
		}
		if isNvidiaDriverPackage(name) {
			return true
		}
	}
	return false
}

// isNvidiaDriverPackage reports whether a package name denotes an NVIDIA
// kernel driver (as opposed to a utility or library).
func isNvidiaDriverPackage(name string) bool {
	// rpm -qa includes the version: "akmod-nvidia-550.54.14-1.fc39.x86_64".
	// Matching on prefixes keeps that working.
	prefixes := []string{
		"nvidia-driver",       // Debian/Ubuntu meta package, RPM Fusion
		"nvidia-dkms",         // Debian/Ubuntu, Arch
		"nvidia-kernel",       // Debian
		"akmod-nvidia",        // Fedora RPM Fusion
		"kmod-nvidia",         // RHEL / RPM Fusion
		"xorg-x11-drv-nvidia", // Fedora/RHEL
		"nvidia-open",         // Arch open kernel modules
		"nvidia-lts",          // Arch LTS kernel
		"nvidia-graphics-drivers",
	}
	for _, p := range prefixes {
		if strings.HasPrefix(name, p) {
			return true
		}
	}
	// Arch: the driver package is literally "nvidia" (pacman -Q prints "nvidia 550.54-1").
	return name == "nvidia"
}
