package remediate

import (
	"fmt"
	"io/fs"
	"os/exec"
	"path/filepath"
	"strings"
)

// This file holds the OS-independent parts of the blacklist-nouveau action so
// they can be unit-tested on any platform. The privileged file and command
// operations live in actions_linux.go.

// nouveauBlacklistPath is the modprobe drop-in nvcheckup manages.
const nouveauBlacklistPath = "/etc/modprobe.d/blacklist-nouveau.conf"

// nouveauBlacklistContent is the exact file content written by the action.
// Every line must satisfy validateNouveauContent so the same content can be
// round-tripped through the journal and restored by undo.
const nouveauBlacklistContent = "# Generated by NVCheckup - blacklist nouveau so the NVIDIA proprietary driver can load\n" +
	"blacklist nouveau\n" +
	"options nouveau modeset=0\n"

// initramfsTool describes how to rebuild the initramfs on a distro family.
// Blacklisting nouveau only in /etc/modprobe.d is not enough on Ubuntu or
// Fedora because the early-boot image carries its own copy of the modprobe
// configuration; without a rebuild nouveau still loads from the initramfs.
type initramfsTool struct {
	Name string
	Args []string
}

// initramfsTools lists the known rebuild tools in preference order:
// Debian/Ubuntu, Fedora/RHEL/openSUSE, Arch.
var initramfsTools = []initramfsTool{
	{Name: "update-initramfs", Args: []string{"-u"}},
	{Name: "dracut", Args: []string{"-f"}},
	{Name: "mkinitcpio", Args: []string{"-P"}},
}

// lookPath resolves a binary on PATH. It is a variable so tests can control
// which initramfs tool appears to be installed.
var lookPath = exec.LookPath

// detectInitramfsTool returns the first known initramfs rebuild tool found on
// PATH, or ok=false when none is installed.
func detectInitramfsTool(look func(string) (string, error)) (initramfsTool, bool) {
	for _, t := range initramfsTools {
		if _, err := look(t.Name); err == nil {
			return t, true
		}
	}
	return initramfsTool{}, false
}

// checkNouveauRestorable reports whether an existing blacklist file's content
// can be recorded as undo information and written back verbatim by Undo. It
// must pass validateNouveauContent (so undo never writes arbitrary directives
// into /etc/modprobe.d) and fit within maxUndoInfoBytes (so validateUndoInfo
// accepts the journal entry later). Apply refuses and Preview says so when
// this fails; nothing is ever overwritten that cannot be put back.
func checkNouveauRestorable(existing string) error {
	if err := validateNouveauContent(existing); err != nil {
		return err
	}
	if len(existing) > maxUndoInfoBytes {
		return fmt.Errorf("content is %d bytes, larger than the %d-byte undo limit", len(existing), maxUndoInfoBytes)
	}
	return nil
}

// normalizeNouveauUndoInfo maps the legacy undo marker written by nvcheckup
// v0.2.0 onto absentSentinel. That version recorded the file path itself
// (exactly nouveauBlacklistPath) to mean "the file did not exist; we created
// it". Only that exact string is translated; anything else is returned as is
// so validateUndoInfo still rejects it.
func normalizeNouveauUndoInfo(undoInfo string) string {
	if undoInfo == nouveauBlacklistPath {
		return absentSentinel
	}
	return undoInfo
}

// packageListHasNvidiaDriver scans package-manager output for an installed
// NVIDIA kernel driver package. It understands:
//   - dpkg -l: lines beginning with "ii" followed by the package name
//   - rpm -qa / pacman -Q: one package per line
//
// It deliberately looks for packages that provide (or build) the kernel
// module rather than any package containing "nvidia": utilities such as
// nvidia-settings, libraries such as libnvidia-* / nvidia-driver-libs, and
// split packages such as nvidia-kernel-common can all be present without a
// usable driver.
func packageListHasNvidiaDriver(output string) bool {
	for _, line := range strings.Split(output, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		name := fields[0]
		// dpkg -l format: "ii  nvidia-driver-550  550.54.14-0ubuntu0  amd64  ..."
		// A two-letter first column is a dpkg status code; only "ii" (installed)
		// and "hi" (installed, on hold) count. "rc", "un", etc. mean removed or
		// never installed. No NVIDIA driver package has a two-letter name, so
		// this cannot mis-skip an rpm or pacman line.
		if len(fields) >= 2 && len(name) == 2 {
			if name != "ii" && name != "hi" {
				continue
			}
			name = fields[1]
		}
		// Strip any dpkg architecture qualifier ("nvidia-dkms-550:amd64").
		if i := strings.IndexByte(name, ':'); i > 0 {
			name = name[:i]
		}
		if isNvidiaDriverPackage(name) {
			return true
		}
	}
	return false
}

// nvidiaModulePackagePrefixes are the version-stripped names of packages that
// provide or build the NVIDIA kernel module.
var nvidiaModulePackagePrefixes = []string{
	"nvidia-driver",        // Debian/Ubuntu meta package (nvidia-driver-550, -open, -server), RPM Fusion/negativo17
	"nvidia-dkms",          // Debian/Ubuntu, Arch
	"nvidia-kernel",        // Debian (nvidia-kernel-dkms, nvidia-kernel-open-dkms)
	"nvidia-open",          // Arch open kernel modules, Debian nvidia-open-kernel-dkms
	"nvidia-lts",           // Arch LTS kernel
	"nvidia-legacy",        // Debian legacy branches (nvidia-legacy-390xx-driver)
	"linux-modules-nvidia", // Ubuntu prebuilt signed modules (linux-modules-nvidia-550-generic)
	"akmod-nvidia",         // Fedora RPM Fusion
	"kmod-nvidia",          // RHEL / RPM Fusion prebuilt modules
	"dkms-nvidia",          // negativo17
	"xorg-x11-drv-nvidia",  // Fedora/RHEL
	"nvidia-graphics-drivers",
}

// nvidiaNonModuleSegments are name components that mark a split package which
// can be installed without a kernel module: libraries, userspace binaries,
// shared configuration, sources, CUDA runtime, and so on.
var nvidiaNonModuleSegments = map[string]bool{
	"libs": true, "lib": true, "libs32": true, "bin": true, "common": true,
	"source": true, "src": true, "kmodsrc": true, "cuda": true, "support": true,
	"utils": true, "settings": true, "devel": true, "dev": true, "doc": true,
	"docs": true, "firmware": true, "headers": true, "persistenced": true,
	"power": true, "modprobe": true, "xconfig": true, "prime": true, "vulkan": true,
	"nonglvnd": true, "egl": true, "gl": true, "compute": true, "encode": true,
	"decode": true, "extra": true, "fbc": true, "ifr": true, "cfg1": true,
}

// stripPackageVersion cuts a package name at the first "-<digit>" boundary,
// which is where dpkg embeds the branch ("nvidia-driver-550") and where rpm
// -qa appends the version ("akmod-nvidia-550.76-1.fc40.x86_64").
func stripPackageVersion(name string) string {
	for i := 1; i+1 < len(name); i++ {
		if name[i] == '-' && name[i+1] >= '0' && name[i+1] <= '9' {
			return name[:i]
		}
	}
	return name
}

// isNvidiaDriverPackage reports whether a package name denotes an NVIDIA
// kernel driver (as opposed to a utility, library, or common-files package).
func isNvidiaDriverPackage(name string) bool {
	// Arch: the driver package is literally "nvidia" (pacman -Q prints "nvidia 550.78-6").
	if name == "nvidia" {
		return true
	}
	// Any library/common/source style component anywhere in the name means the
	// package does not carry the module, whatever its family prefix is
	// (nvidia-driver-libs, nvidia-kernel-common, nvidia-kernel-source-550,
	// xorg-x11-drv-nvidia-cuda, nvidia-legacy-390xx-driver-libs).
	for _, seg := range strings.Split(name, "-") {
		if nvidiaNonModuleSegments[seg] {
			return false
		}
	}
	base := stripPackageVersion(name)
	for _, p := range nvidiaModulePackagePrefixes {
		if base == p || strings.HasPrefix(base, p+"-") {
			return true
		}
	}
	return false
}

// dkmsStatusHasInstalledNvidia reports whether "dkms status" output shows an
// nvidia module that is built AND installed for the given running kernel. It
// understands both dkms 2.x ("nvidia, 550.54.14, 6.5.0-28-generic, x86_64:
// installed") and dkms 3.x ("nvidia/550.54.14, 6.5.0-28-generic, x86_64:
// installed") line shapes. "added" (source registered, never built) and
// "built" (compiled but not placed under /lib/modules) do not count, and
// neither does a module installed only for a different kernel: that is the
// state after a kernel upgrade whose DKMS rebuild failed.
func dkmsStatusHasInstalledNvidia(output, kernel string) bool {
	kernel = strings.TrimSpace(kernel)
	if kernel == "" {
		return false
	}
	for _, line := range strings.Split(output, "\n") {
		line = strings.TrimSpace(line)
		lower := strings.ToLower(line)
		if !strings.HasPrefix(lower, "nvidia") {
			continue
		}
		colon := strings.LastIndex(line, ":")
		if colon < 0 {
			continue
		}
		status := strings.ToLower(strings.TrimSpace(line[colon+1:]))
		if !strings.HasPrefix(status, "installed") {
			continue
		}
		// The kernel version is one of the comma-separated fields before the status.
		for _, f := range strings.Split(line[:colon], ",") {
			if strings.TrimSpace(f) == kernel {
				return true
			}
		}
	}
	return false
}

// isNvidiaModuleFile reports whether a file name is the NVIDIA kernel module
// in any of the compressed forms distros ship (nvidia.ko, nvidia.ko.xz,
// nvidia.ko.zst, nvidia.ko.gz).
func isNvidiaModuleFile(name string) bool {
	return name == "nvidia.ko" || strings.HasPrefix(name, "nvidia.ko.")
}

// findBuiltNvidiaModule walks modulesDir (normally /lib/modules/<uname -r>)
// and returns the path of the first nvidia.ko* it finds, or "" when none
// exists. It covers DKMS output (updates/dkms), distro-built packages
// (kernel/drivers/video, kernel/nvidia-550) and anything else under the
// running kernel's module tree. A missing directory simply yields "".
func findBuiltNvidiaModule(modulesDir string) string {
	if strings.TrimSpace(modulesDir) == "" {
		return ""
	}
	found := ""
	_ = filepath.WalkDir(modulesDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			// Unreadable subtree: keep looking elsewhere.
			if d != nil && d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		if !d.IsDir() && isNvidiaModuleFile(d.Name()) {
			found = path
			return fs.SkipAll
		}
		return nil
	})
	return found
}

// driverInstallVerdict combines the three pieces of evidence about an NVIDIA
// kernel driver into a decision. It is the pure core of nvidiaDriverInstalled.
//
//   - modinfoOK: "modinfo nvidia" succeeded, so the module is resolvable for
//     the running kernel. Sufficient on its own.
//   - packageEvidence: the package-manager query that listed a driver package
//     ("" when none did).
//   - moduleEvidence: path of a built nvidia.ko* for the running kernel, or a
//     note that dkms status reports it installed ("" when neither).
//
// A package alone is NOT enough: after a failed DKMS build (missing headers,
// Secure Boot signing failure, unsupported new kernel) the package is present
// but no module exists, and blacklisting nouveau in that state boots to a
// machine with no display driver at all.
func driverInstallVerdict(modinfoOK bool, packageEvidence, moduleEvidence, kernel string) (evidence string, ok bool) {
	switch {
	case modinfoOK:
		return "kernel module 'nvidia' is available (modinfo nvidia)", true
	case packageEvidence != "" && moduleEvidence != "":
		return fmt.Sprintf("NVIDIA driver package installed (%s) and %s", packageEvidence, moduleEvidence), true
	case packageEvidence != "":
		k := kernel
		if k == "" {
			k = "the running kernel"
		}
		return fmt.Sprintf("NVIDIA driver package is installed (%s) but no nvidia kernel module is built for %s: "+
			"modinfo nvidia failed, no nvidia.ko* exists under /lib/modules/%s and dkms status does not list nvidia as installed for it. "+
			"This is the state left by a failed DKMS build (missing kernel headers, Secure Boot signing, or an unsupported kernel)",
			packageEvidence, k, kernel), false
	default:
		return "no NVIDIA driver detected (modinfo nvidia failed and no nvidia driver package is installed)", false
	}
}
